<?php

declare(strict_types=1);

namespace ItalyStrap\Asset\Infrastructure;

use ItalyStrap\Config\ConfigInterface;
use ItalyStrap\Theme\Infrastructure\Config\ConfigThemeProvider;

use function array_filter;
use function array_key_exists;
use function array_merge;
use function array_unique;
use function array_values;
use function file_exists;
use function filemtime;
use function is_array;
use function ltrim;
use function pathinfo;
use function realpath;
use function str_replace;

use const PATHINFO_DIRNAME;
use const PATHINFO_FILENAME;

/**
 * Resolves a theme asset (script or style) by searching child theme first,
 * then parent theme. Optionally reads the companion `.asset.php` file
 * generated by `@wordpress/scripts` for version hash and dependencies.
 *
 * The `.asset.php` file is optional — it only exists after a production build.
 * When absent, version falls back to filemtime() and dependencies to [].
 */
class ThemeAssetResolver
{
    private ConfigInterface $config;

    public function __construct(ConfigInterface $config)
    {
        $this->config = $config;
    }

    /**
     * Resolve a relative asset path to its URL, version, and dependencies.
     *
     * @param string   $relative_path         Primary relative path (e.g. 'build/customizer/live-preview.js').
     * @param string[] $fallback_relative_paths Additional candidates tried in order if the primary is not found.
     * @return array{url: string, dependencies: array<string>, version: string|null}
     */
    public function resolve(string $relative_path, array $fallback_relative_paths = []): array
    {
        $candidates = $this->buildCandidates($relative_path, $fallback_relative_paths);
        $located    = $this->locate($candidates);

        if ([] === $located) {
            return [
                'url'          => $this->urlFor(
                    (string) $this->config->get(ConfigThemeProvider::TEMPLATE_DIR_URI),
                    $candidates[0] ?? $relative_path
                ),
                'dependencies' => [],
                'version'      => null,
            ];
        }

        $metadata = $this->readMetadata($located['path']);

        $version = $metadata['version'];
        if (null === $version && file_exists($located['path'])) {
            $version = (string) filemtime($located['path']);
        }

        return [
            'url'          => $this->urlFor($located['uri'], $located['relative_path']),
            'dependencies' => $metadata['dependencies'],
            'version'      => $version,
        ];
    }

    /**
     * @param string[] $candidates
     * @return array{path: string, relative_path: string, uri: string}|array{}
     */
    private function locate(array $candidates): array
    {
        $roots = [
            [
                'path' => (string) realpath((string) $this->config->get(ConfigThemeProvider::STYLESHEET_DIR)),
                'uri'  => (string) $this->config->get(ConfigThemeProvider::STYLESHEET_DIR_URI),
            ],
            [
                'path' => (string) realpath((string) $this->config->get(ConfigThemeProvider::TEMPLATE_DIR)),
                'uri'  => (string) $this->config->get(ConfigThemeProvider::TEMPLATE_DIR_URI),
            ],
        ];

        foreach ($candidates as $candidate) {
            $candidate = ltrim(str_replace('\\', '/', $candidate), '/');
            foreach ($roots as $root) {
                if ('' === $root['path']) {
                    continue;
                }
                $full_path = $root['path'] . '/' . $candidate;
                if (file_exists($full_path)) {
                    return [
                        'path'          => $full_path,
                        'relative_path' => $candidate,
                        'uri'           => $root['uri'],
                    ];
                }
            }
        }

        return [];
    }

    /**
     * Read the optional `.asset.php` companion file.
     *
     * @return array{dependencies: array<string>, version: string|null}
     */
    private function readMetadata(string $asset_path): array
    {
        $metadata_path = pathinfo($asset_path, PATHINFO_DIRNAME)
            . '/'
            . pathinfo($asset_path, PATHINFO_FILENAME)
            . '.asset.php';

        if (!file_exists($metadata_path)) {
            return ['dependencies' => [], 'version' => null];
        }

        $metadata = require $metadata_path;

        if (!is_array($metadata)) {
            return ['dependencies' => [], 'version' => null];
        }

        return [
            'dependencies' => array_values((array) ($metadata['dependencies'] ?? [])),
            'version'      => array_key_exists('version', $metadata) ? (string) $metadata['version'] : null,
        ];
    }

    private function urlFor(string $base_uri, string $relative_path): string
    {
        return rtrim($base_uri, '/') . '/' . ltrim($relative_path, '/');
    }

    /**
     * @param string[] $fallbacks
     * @return string[]
     */
    private function buildCandidates(string $relative_path, array $fallbacks): array
    {
        return array_values(
            array_unique(
                array_filter(
                    array_merge([$relative_path], $fallbacks)
                )
            )
        );
    }
}
