<?php

declare(strict_types=1);

namespace ItalyStrap\Asset\Infrastructure;

use ItalyStrap\Asset\Version\VersionInterface;
use SplFileInfo;

use function file_exists;
use function is_array;
use function pathinfo;

use const PATHINFO_DIRNAME;
use const PATHINFO_FILENAME;

/**
 * Reads the version hash from the companion `.asset.php` file generated by
 * `@wordpress/scripts` at build time. The file is optional — it will not exist
 * in development or CI before a build is run. Falls back to the file's mtime.
 */
final class WpScriptsVersion implements VersionInterface
{
    public function version(SplFileInfo $fileInfo, array $config)
    {
        $metadata_path = pathinfo((string) $fileInfo->getRealPath(), PATHINFO_DIRNAME)
            . '/'
            . pathinfo((string) $fileInfo->getFilename(), PATHINFO_FILENAME)
            . '.asset.php';

        if (file_exists($metadata_path)) {
            $metadata = require $metadata_path;
            if (is_array($metadata) && isset($metadata['version']) && '' !== (string) $metadata['version']) {
                return (string) $metadata['version'];
            }
        }

        return (string) $fileInfo->getMTime();
    }
}
