name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Test on PHP ${{ matrix.php_versions }}

    runs-on: ubuntu-16.04
    continue-on-error: ${{ matrix.php_versions == '8.1' }}

    strategy:
      matrix:
        php_versions: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
          coverage: xdebug2
          # extensions: gd, zip
          tools: composer:v1

      - uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist --ignore-platform-reqs"

      - name: Run test suite
        run: vendor/bin/codecept run unit --coverage-text

      - name: Run infection suite
        run: vendor/bin/infection --threads=4

#      - name: Run PHPBench suite
#        run: vendor/bin/phpbench run --report=performance
